title: Linux Sincero
markdown: kramdown

# for atom feed
author:
  name: Max Cleiton
  email: maxcleiton@live.com

url: "https://maxxcleiton.github.io/"

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-google_search_console_verification_file

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]

google_search_console:
  verification_file_code: 6a9892984c4ee862